blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussion Discord
    url: https://discord.gg/SwBDTRpwa7
    about: Pour les questions gÃ©nÃ©rales ou l'aide, rejoignez notre Discord
  - name: ğŸ“– Documentation
    url: https://github.com/thogio8/datactl/blob/main/README.md
    about: Consultez la documentation avant de crÃ©er une issue
